### PR TITLE
Load Twitter keys/secrets from YAML config file

### PR DESCRIPTION
**Pull request by hugovk**
Re: https://github.com/edsu/twarc/issues/64

Add a `--yaml` command-line argument. If the Twitter keys and secrets haven't been found in an env variable or in their own arguments, then attempt to load them from this .yaml file.

Other things:

 * I removed the restriction to build only master, as its good practice to make PRs from branches, not master, and I wanted to test my changes on the CI. Let me know if you want the restriction putting back.

 * I put back the coverage and static analysis stuff in the build. This command had been causing problems:

```bash
coverage run --source twarc -m python setup.py test --verbose
No module named 'python'
```
The correct command is:
```bash
coverage run --source twarc setup.py test --verbose
```

### CODE REVIEW

**Comment by edsu** [comment]
This looks like it is shaping up nicely. If no keys are found in the environment and --yaml hasn't been used do you think it would be useful if twarc prompted the user for the keys and saved them to some default location for the yaml file, like ~/.twarc?

**Comment by hugovk** [comment]
Good idea, I'll update the PR.

**Comment by hugovk** [comment]
PR updated. Keys are prompted for and saved to `~/twarc.yaml`. Would you prefer `~/twarc`?

Perhaps the default location for the `--yaml` option should be updated to match.

**Comment by edsu** [comment]
~/.twarc.yaml works too -- thanks!

**Comment by hugovk** [comment]
Updated `--yaml` default to match. Also flake8 changes.

**Comment by hugovk** [comment]
Build passed on branch: https://travis-ci.org/hugovk/twarc

**Comment by edsu** [comment]
This is great. When updating my own dev environment I see that pyyaml requires compiling C libraries. This seems like a bit of a pain honestly. Is there any reason not use something that comes with Python: json or configparser, etc? Or am I being overly conservative here?

**Comment by hugovk** [comment]
At least for me `pip install pyaml` was painless on OS X and Windows. I didn't notice if it built anything. But if the installation doesn't go smoothly on other platforms, I can certainly change it to JSON or ConfigParser. 

One good thing about YAML over JSON is the output is much cleaner, it's easier to create a valid file by hand; and it's a little bit simple than ConfigParser.

Here's a comparison: http://martin-thoma.com/configuration-files-in-python/

What do you think?

**Comment by edsu** [comment]
If it's ok with you I'd like to switch it over to [ConfigParser](https://docs.python.org/2/library/configparser.html). I like the fact that it's core Python and easily supports multiple sections which could correspond to profiles as it works with [aws-cli](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-multiple-profiles). This will make it easy to run twarc using different credentials as needed ; which can be handy for concurrent archiving jobs.

That being said, I don't expect you to do this if you don't want to. I can run with what you have if you've pushed it as far along as you can right now.

**Comment by hugovk** [comment]
Sounds good, I'm happy to switch it. I'll do it in the next few days.

**Comment by hugovk** [comment]
Updated with ConfigParser, build passes on my repo:
https://travis-ci.org/hugovk/twarc/builds/65672474

**Comment by edsu** [comment]
Sorry for the delay, this is really, really super @hugovk -- thanks for the contribution!

:cake: :balloon: :tada:

**Comment by hugovk** [comment]
Happy to help!

**Pull request merged**
