### PR TITLE
Create valid GeoJSON

### PR DESCRIPTION
**Pull request by alexgleith**
Reverted the geometry storage to ensure valid GeoJSON is being stored.

### CODE REVIEW

**Comment by edsu** [comment]
Thanks, but it's not needed.

**Comment by edsu** [comment]
I just caught up with some of your other messages and see why you want to have this. Sorry!

**Comment by alexgleith** [comment]
Ok, well you're the boss, but I think it's a mistake not using standard GeoJSON. (Ah, now I see your edit!)

And, I seem to have missed the second commit, but I think there's a bug in that all features are getting passed through this utility now, rather than only the ones with a location.

https://github.com/alexgleith/twarc/blob/bounding-boxes-valid-geojson/utils/geojson.py

**Comment by edsu** [comment]
Sorry for the confusion. I now see your point about the Polygon and the geo-less tweets being passed through. I think this has been resolved now?

**Comment by alexgleith** [comment]
Yep, I think we're all good!

**Comment by edsu** [comment]
Thanks for taking the time to contribute this, and for your patience :-D

**Comment by alexgleith** [comment]
No worries, I'm keen to do more contribution to things like this rather than changing my local version and ignoring the main repo! Thanks for building the project =)

**Pull request merged**
