### PR TITLE
Adds sample stream, user timeline, and user lookup.

### PR DESCRIPTION
**Pull request by kerchner**
And some PEP8 fixes.

### CODE REVIEW

**Comment by kerchner** [comment]
@edsu please let me know if you have any questions regarding this PR

**Comment by edsu** [comment]
Oops! For some reason I missed this until now. I will take a look ASAP.

**Comment by edsu** [comment]
Looks great! I made a few minor tweaks and released as [v0.7.0](https://pypi.python.org/pypi/twarc/0.7.0)!

**Comment by kerchner** [comment]
Thanks @edsu !   This helps as we'll be able to point to https://pypi.python.org/pypi/twarc/0.7.0, rather than our fork, in the (very soon) upcoming release of [SFM](https://github.com/gwu-libraries/sfm-ui) 1.0 !

**Pull request merged**
